version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "step-function"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1jfev9reicy3x"
s3_prefix = "step-function"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
